config/routes.rb
Rails.application.routes.draw do
  
  
  resources :links
  get '/all' => 'static_pages#all'
  get ':slug' => 'links#show'
  get 'static_pages/home'
  root 'static_pages#home'
  namespace :api do
    namespace :v1 do
      resources :links, only: [:create]
    end
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  after_create :generate_slug
  VALID_URL_REGEX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}/
  validates :given_url, 
              presence: true, 
              length: { maximum: 255 },
              format: { with: VALID_URL_REGEX, message: "Invalid URL format" }
  def generate_slug
    self.slug = self.id.to_s(36)
    self.save
  end
  def display_slug
    ENV['BASE_URL'] + self.slug
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :destroy_session
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  def destroy_session
    request.session_options[:skip] = true
  end
    

  def not_found
    return api_error(status: 404, errors: 'Not found')
  end
  
  def api_error(status: 500, errors: [])
    unless Rails.env.production?
      puts errors.full_messages if errors.respond_to? :full_messages
    end
    head status: status and return if errors.empty?

    render json: jsonapi_format(errors).to_json, status: status
  end
  
  def jsonapi_format(errors)
    return errors if errors.is_a? String
    errors_hash = {}
    errors.messages.each do |attribute, error|
      array_hash = []
      error.each do |e|
        array_hash << {attribute: attribute, error_message: e}
      end
      errors_hash.merge!({ 'error' => array_hash })
    end

    return errors_hash
  end
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::V1::BaseController 
  
  
  
  def create
    @link = Link.new(:given_url => params[:url])
    return api_error(status: 422, errors: @link.errors) unless @link.valid?

    @link.save!

    render(
      json: Api::V1::LinkSerializer.new(@link).to_json,
      status: 201
    )
  end
  
  private
  def link_params
      params.permit(:url).delete_if{ |k,v| v.nil?}
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show]

  def index
    @links = Link.all
  end

  def show
    if params[:slug]
      @link = Link.find_by(slug: params[:slug])
      if redirect_to @link.given_url
        @link.save
      end
    else
      @link = Link.find(params[:id])
    end
  end

  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to root_path, notice: 'Link was successfully created.' }
        format.js
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_link
      @link = Link.find_by(slug: params[:slug])
    end

    def link_params
      params.require(:link).permit(:given_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @link = Link.new
  end
  def all
    @link = Link.new
    @links = Link.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Ruby on Rails Assignment
    by Tony Vincent
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>

app/views/layouts/_new_link.html.erb
<div class="row">

<%= render 'links/form' %>
</div>

<div class="result">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
  <![endif]-->
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   '#' %></li>
          <li><%= link_to "Help",   '#' %></li>
          <li><%= link_to "More", '#' %></li>
        </ul>
      </nav>
    </div>
  </header>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link, remote: true) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= link_to image_tag("logo.jpg"), root_path %>
  </div>
  <div>&nbsp</div>
  <div class="field">
    <%= f.text_field :given_url, :class => "form-control", :placeholder => "Paste a link to shorten" %>
  </div>
  <div class="actions">
    <%= f.submit 'Shorten Me', :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/links/create.js.erb
$('.result').append('<p class="short_url">Your Shortened Link: <%= link_to @link.display_slug, @link.display_slug, target: "_blank" %></p>')

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Given url</th>
      <th>Slug</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.given_url %></td>
        <td><%= link.slug %></td>
        <td><%= link.title %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p class="title"><%= @link.title %></p>
<p class="short_url"><%= link_to @link.display_slug, @link.display_slug, target: '_blank' %></p>
<ul class="click_time">
  <li><span class="time"><%= time_ago_in_words(@link.created_at) %> ago</span></li>
</ul>
<p class="long_url"><%= link_to @link.given_url, @link.given_url %></p>

<%= link_to 'Back', root_path %>

app/views/static_pages/all.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Given url</th>
        <th>Short Link</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%= link.given_url %></td>
          <td><%= link_to link.display_slug, link.slug, target: '_blank' %></td>
          <td><%= link_to 'Show', link %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<p class="bottom_nav"><%= link_to 'Shorten now', root_path %></p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is a url-shortening
    <a href="http://www.ruby-software.com/">RubySoftware</a>
    assignment application.
  </h2>
  <%= render 'layouts/new_link' %>
</div>